all:
	javac -classpath .. \
		Behaviour.java \
		BehaviouralEvent.java \
		BehaviourViolation.java \
		BehaviourBuilder.java \
		events/Value.java \
		events/Constant.java \
		events/Variable.java \
		events/MethodInvoked.java
